version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nodejs
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile.nodejs
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: db_fullcycle
      MYSQL_USER: fullcycle
      MYSQL_PASSWORD: 123456